# Generated by Django 5.0.6 on 2024-06-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='classification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='generation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
